// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lLoyeijJR4g3DBDbjy32HqBTtILNCMw',
    appId: '1:539664849674:web:37716e1754820e55b9b8f3',
    messagingSenderId: '539664849674',
    projectId: 'mynotes-dev-peako',
    authDomain: 'mynotes-dev-peako.firebaseapp.com',
    storageBucket: 'mynotes-dev-peako.appspot.com',
    measurementId: 'G-J20Q17G67P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFT4wcGrt4pyfl2kAgxZQdgHxTcmusiKI',
    appId: '1:539664849674:android:a4b7f22458f73141b9b8f3',
    messagingSenderId: '539664849674',
    projectId: 'mynotes-dev-peako',
    storageBucket: 'mynotes-dev-peako.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_crPnlpaGMLNHatEOds5C34BqrsaGO30',
    appId: '1:539664849674:ios:8c77adf49b4f9618b9b8f3',
    messagingSenderId: '539664849674',
    projectId: 'mynotes-dev-peako',
    storageBucket: 'mynotes-dev-peako.appspot.com',
    iosClientId: '539664849674-uu2dn0n7e3q144n1ep20s7htingqk422.apps.googleusercontent.com',
    iosBundleId: 'dev.peako.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_crPnlpaGMLNHatEOds5C34BqrsaGO30',
    appId: '1:539664849674:ios:8c77adf49b4f9618b9b8f3',
    messagingSenderId: '539664849674',
    projectId: 'mynotes-dev-peako',
    storageBucket: 'mynotes-dev-peako.appspot.com',
    iosClientId: '539664849674-uu2dn0n7e3q144n1ep20s7htingqk422.apps.googleusercontent.com',
    iosBundleId: 'dev.peako.mynotes',
  );
}
